### ISSUE TITLE
Docs build fails due to conda netcdf issue

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#166]
The documentation builds locally, but fails in the CI (same problem occurs over on RTD):

https://github.com/CWorthy-ocean/roms-tools/actions/runs/11370740902/job/31632008850?pr=165

```
Collecting netcdf4 (from roms-tools==0.1.dev1)
  Downloading netcdf4-1.7.1.post2.tar.gz (827 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.8/827.8 kB 77.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Package hdf5 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `hdf5.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'hdf5', required by 'virtual:world', not found
      reading from setup.cfg...
          HDF5_DIR environment variable not set, checking some standard locations ..
      checking /home/runner/micromamba/envs/romstools/include...
      hdf5 headers not found in /home/runner/micromamba/envs/romstools/include
      checking /home/runner/micromamba/envs/romstools/Library/include...
      hdf5 headers not found in /home/runner/micromamba/envs/romstools/Library/include
      checking /home/runner/include...
      hdf5 headers not found in /home/runner/include
      checking /usr/local/include...
      hdf5 headers not found in /usr/local/include
      checking /sw/include...
      hdf5 headers not found in /sw/include
      checking /opt/include...
      hdf5 headers not found in /opt/include
      checking /opt/local/include...
      hdf5 headers not found in /opt/local/include
      checking /opt/homebrew/include...
      hdf5 headers not found in /opt/homebrew/include
      checking /usr/include...
      hdf5 headers not found in /usr/include
      Traceback (most recent call last):
        File "/home/runner/micromamba/envs/romstools/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line [35](https://github.com/CWorthy-ocean/roms-tools/actions/runs/11370740900/job/31631201289?pr=165#step:4:36)3, in <module>
          main()
          ~~~~^^
        File "/home/runner/micromamba/envs/romstools/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/micromamba/envs/romstools/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-e118lk_0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-e118lk_0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-e118lk_0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 277, in <module>
        File "<string>", line 226, in _populate_hdf5_info
      ValueError: did not find HDF5 headers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

Strangely, installing the netcdf dependency in the other CI jobs with conda works perfectly.

**Comment by NoraLoose** [comment]
Why does it fail for the docs build but not the other CI jobs? It seems to be related to how the `netcdf4` dependency is downloaded. Not sure why the downloading is different for the two cases - the conda commands are the same in both cases.

### For docs build: Source Distribution

It tries to download a source distribution (netcdf4-1.7.1.post2.tar.gz), which is a tarball of the package's source code.
This usually happens when no suitable pre-built binary wheel is available for your specific platform or Python version.

### In other CI jobs: Pre-built Binary Wheel

It finds a pre-built binary wheel (netCDF4-1.7.1.post2-cp310-cp310-manylinux_2_17_x86_64.whl), which is a ready-to-install package specific to your Python version (cp310 for Python 3.10) and platform (manylinux for Linux).
The .whl file is preferred because it’s quicker to install compared to building from the source distribution.

**Comment by NoraLoose** [comment]
@dafyddstephenson any ideas for what is going on? Looks like in C-Star it's downloading the pre-built binary wheel (which always works).

**Comment by dafyddstephenson** [comment]
I have noticed recently that tests sometimes fail to get out of the gate on push to my branches but pass on the associated PR. Been a bit swamped to investigate, will take a look if this is the same thing / the issue is systematic on my end
